### ISSUE TITLE
Annotation file for RNA-seq variant calling

### ISSUE THREAD

**Issue by doncarlos999** [gatk-workflows/gatk3-4-rnaseq-germline-snps-indels#4]
Hi,
I am trying to follow your workflow for RNA-seq variant calling but I am having trouble building the STAR index. I am using the HG38 fasta found here :
ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/hg38/Homo_sapiens_assembly38.fasta.gz
But there is no associated annotation file. All the annotation files I have tried so far give an error at the end of the STAR indexing process.
There is an annotation file referenced in the file: 
rna-germline-variant-calling.inputs.json
("RNAseq.annotationsGTF": "gs://gatk-test-data/intervals/star.gencode.v19.transcripts.patched_contigs.gtf",)
Would it be possible to upload this to the GATK resource pack? Or give me a link to somewhere that I can download it?
Thanks

**Comment by bshifaw** [comment]
Hello, 
All the  reference and resources in the json are publicly available in google cloud buckets. You'll need a google account to access the buckets. The above file can be downloaded useing the following link https://console.cloud.google.com/storage/browser/gatk-test-data/intervals/?project=broad-dsde-outreach

Any of the other files should be accessible within the gatk-test-data or broad-references bucket. https://console.cloud.google.com/storage/browser/gatk-test-data?project=broad-dsde-outreach
https://console.cloud.google.com/storage/browser/broad-references?project=broad-dsde-outreach
